In [1]:
a = float(input('Enter first number: '))
b = float(input('Enter second number: '))
c = float(input('Enter third number: '))
if (a >b) and (a > c):
   largest = s
elif (b > a) and (b > c):
   largest = b
else:
   largest = c
print("The largest number is", largest)

Enter first number: 5
Enter second number: 10
Enter third number: 20
The largest number is 20.0


In [2]:
a = int(input("Enter the number: "))
print("Multiplication Table of", a)
for i in range(1, a+1):
   print(a,"X",i,"=",a * i)

Enter the number: 10
Multiplication Table of 10
10 X 1 = 10
10 X 2 = 20
10 X 3 = 30
10 X 4 = 40
10 X 5 = 50
10 X 6 = 60
10 X 7 = 70
10 X 8 = 80
10 X 9 = 90
10 X 10 = 100


In [3]:
r=int(input("Enter the radius of cylinder : "))
h=int(input("Enter the height of cylinder : "))

print("Surface Area of cylinder =  ",(2*3.14*r*r)+(2*3.14*r*h))
print("Volume of cylinder =  ",3.14*r*r*h)

Enter the radius of cylinder : 3
Enter the height of cylinder : 5
Surface Area of cylinder =   150.72
Volume of cylinder =   141.29999999999998


In [1]:
sentence=input("Enter the Character: ")
word=input("Enter the Word to be replaced: ")
new_word=input("Enter the new Word: ")
arr=sentence.split()
for i in range(len(arr)):
    if arr[i]==word:
        arr[i]=new_word
        new_sentence=""
        for i in range(len(arr)):
         new_sentence= new_sentence+arr[i]+" "
        print(new_sentence)

Enter the Character: My name is THomson
Enter the Word to be replaced: THomson
Enter the new Word: Thomson
My name is Thomson 


In [2]:
email=input("Enter the email id: ")
arr=email.split('@')
if len(arr)!=2:
    print("Invalid email")
else:
    if arr[1]=="gmail.com" or arr[1]=="yahoo.com":
        print("Valid email")
    else:
        print("Invalid email")

Enter the email id: thomsonthomas@gmail.com
Valid email


In [3]:
n=int(input("Enter the number of elements"))
list=[]
for i in range(0,n):
	print("Enter element",i+1," :",end=" ")
	list.append(int(input()))
print(list)
x=int(input("Enter element to be removed : "))
while(x in list):
	list.remove(x)
print(list)

Enter the number of elements5
Enter element 1  : 1
Enter element 2  : 2
Enter element 3  : 3
Enter element 4  : 4
Enter element 5  : 5
[1, 2, 3, 4, 5]
Enter element to be removed : 3
[1, 2, 4, 5]


In [4]:
def Tuple(A):
   evenlist = []
   oddlist = []
   for i in A:
      if (i % 2 == 0):
         evenlist.append(i)
      else:
         oddlist.append(i)
   print("Even Tuple:", tuple(evenlist))
   print("Odd Tuple:", tuple(oddlist))
A=[]
n=int(input("Enter the size of the tuple :"))
print("Enter the element in tuple :")
for i in range(int(n)):
   A.append(int(input()))
Tuple(A)

Enter the size of the tuple :6
Enter the element in tuple :
1
2
3
4
5
6
Even Tuple: (2, 4, 6)
Odd Tuple: (1, 3, 5)


In [5]:
books={'book1':100,'book2':150,'book3':200}
print("Books :",books)
newbook=input("Enter the book to add: ")
n=int(input("Enter the number of stocks: "))
books.update({newbook:n})
print("Updated Books :",books)
x=input("Enter the book to delete : ")
element=books.pop(x)
print("Newly Updated Books :",books)

Books : {'book1': 100, 'book2': 150, 'book3': 200}
Enter the book to add: book4
Enter the number of stocks: 120
Updated Books : {'book1': 100, 'book2': 150, 'book3': 200, 'book4': 120}
Enter the book to delete : book1
Newly Updated Books : {'book2': 150, 'book3': 200, 'book4': 120}


In [6]:
import numpy as mat
mat1=mat.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=mat.array([[7,8,9],[1,2,3],[4,5,6]])
sum=mat1+mat2
print("First Matrix :\n",mat1)
print("Second Matrix :\n",mat2)
print("Sum Matrix : \n",sum)

First Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix :
 [[7 8 9]
 [1 2 3]
 [4 5 6]]
Sum Matrix : 
 [[ 8 10 12]
 [ 5  7  9]
 [11 13 15]]
